---
- hosts: all
  gather_facts: False
  roles:
    - role: arubanetworks.aoscx_role
  tasks:
    - name: Create VLAN 200 with description
      aoscx_vlan:
        vlan_id: 200
        description: This is VLAN 200
    - name: Create VLAN 300 with description and name
      aoscx_vlan:
        vlan_id: 300
        name: UPLINK_VLAN
        description: This is VLAN 300
    - name: Delete VLAN 300
      aoscx_vlan:
        vlan_id: 300
        state: delete