---
- hosts: all
  gather_facts: False
  tags:
    - backup
  vars:
    tftp_server: 10.100.1.100
    config_file: "{{inventory_hostname}}.conf"
  tasks:
    - name: Copy Running Config to TFTP Server
      arubaos_cx_ssh_cli:
        ip: "{{ansible_host}}"
        user: "{{ansible_user}}"
        password: "{{ansible_password}}"
        commands: ["copy running-config tftp://{{tftp_server}}/{{config_file}} cli vrf mgmt"]

- hosts: all
  gather_facts: False
  tags:
    - restore
  vars:
    tftp_server: 10.100.1.100
    config_file: "{{inventory_hostname}}.conf"
  tasks:
    - name: Copy Stored Local Config to Startup through TFTP
      arubaos_cx_ssh_cli:
        ip: "{{ansible_host}}"
        user: "{{ansible_user}}"
        password: "{{ansible_password}}"
        commands: ["copy tftp://{{tftp_server}}/{{config_file}} startup-config vrf mgmt"]

    - name: Copy Startup to Running Config
      arubaos_cx_ssh_cli:
        ip: "{{ansible_host}}"
        user: "{{ansible_user}}"
        password: "{{ansible_password}}"
        commands: ["copy startup-config running-config"]
