- hosts: access_1,access_2
  gather_facts: False
  roles:
    - role: arubanetworks.aoscx_role
  vars:
    vlans: ['10', '20', '30', '40', '50', '60', '70']
    interfaces: ['3', '4', '5', '6']
  tasks:
    - name: Create VLANs
      aoscx_vlan:
        vlan_id: "{{item}}"
      loop: "{{vlans}}"

    - name: Trunk VLANs on Interfaces
      aoscx_l2_interface:
        interface: "1/1/{{item}}"
        vlan_mode: trunk
        vlan_trunks: "{{vlans}}"
      loop: "{{interfaces}}"