- hosts: core
  gather_facts: False
  roles:
  - role: arubanetworks.aoscx_role
  tasks:
    - name: Create Banner
      aoscx_banner:
        banner_type: banner
        banner: |
          **************************************************************
          ************************WELCOME*******************************
          ***************************TO*********************************
          ************************THE AOS-CX****************************
          **********************ANSIBLE WORKSHOP************************
          **************************************************************